version: '3'

volumes:
  opt-splunk-etc:

services:
  splunk:
    #build: .
    hostname: splunk
    image: splunk/splunk:latest
    environment:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_ENABLE_LISTEN: "9997"
      SPLUNK_ADD: "tcp 1514"
      SPLUNK_PASSWORD: "<password of choice>"
    volumes:
      - opt-splunk-etc:/opt/splunk/etc
      - <path to custom log directory>:/opt/splunk/var
    ports:
      - "9999:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"
